### ISSUE TITLE
How is pose generated for real data?

### ISSUE THREAD

**Issue by dongchen-yang** [lwwu2/fipt#1]
Hi, we tried to generate poses for real data using COLMAP, but we observed some huge driftings. Do you have any recommended softwares to generate poses?

**Comment by Jerrypiglet** [comment]
Hey @dyang111 I think you are asking about how we acquired poses for real world captures? We tried both Colmap and Superglue, check [here](https://github.com/Jerrypiglet/rui-indoorinv-data/blob/fipt/README_real.md#run-the-pipeline). 

I believe the quality and number of valid poses acquired with both tools largely depend on the image quality, scene appearance and calibration etc. For example, if you have lot of motion blur, textureless regions (but Superglue should be fairly robust to this), bad calibrated intrinsics, or limited view coverage, those might impact the poses you get from both methods.

**Comment by dongchen-yang** [comment]
Yes, we are trying to get poses for real world captures. Thank you for your suggestion!
