### ISSUE TITLE
How to get the estimated geometry?

### ISSUE THREAD

**Issue by zk1009** [lwwu2/fipt#2]
Hi，thank you for the great work! 
I noticed that your data includes ground truth geometry. How can I use monosdf to estimate the geometry of your data? I found https://github.com/Jerrypiglet/monosdf, but I couldn't find some of the files mentioned in the readme, such as convert_mitsubaScene3D_to_monosdf.py and kitchen_hdr_est_mlp.conf.

**Comment by Jerrypiglet** [comment]
Hey there, please check [here](https://github.com/Jerrypiglet/rui-indoorinv-data/blob/fipt/README_indoor_synthetic.md#export-to-monosdf-format) for downloading scene files and export for MonoSDF training, and the `fipt` branch of our customized MonoSDF repo: [updated README](https://github.com/Jerrypiglet/monosdf/tree/fipt) for full instructions on getting DPT depth/normals and training models. Let us know if you have further questions.
