### ISSUE TITLE
Visualize the Radiance Cache

### ISSUE THREAD

**Issue by dongchen-yang** [lwwu2/fipt#3]
Hi, is there a way to visualize the precomputed radiance, i.e. the vslf.npz file?

**Comment by lwwu2** [comment]
Hi,

It can be visualized like follow:

```
import torch
import torch.nn.functional as NF

import mitsuba
mitsuba.set_variant('cuda_ad_rgb')

import os
from utils.dataset import SyntheticDataset
from utils.path_tracing import ray_intersect
from model.slf import VoxelSLF

import matplotlib.pyplot as plt



# read dataset and geometry
dataset_path = '../data/indoor_synthetic/kitchen'
dataset = SyntheticDataset(dataset_path,pixel=False,split='train',ray_diff=False)
img_hw = dataset.img_hw

scene = mitsuba.load_dict({
    'type': 'scene',
    'shape_id':{
        'type': 'obj',
        'filename': os.path.join(dataset_path,'scene.obj')
    }
})

device = torch.device(0)


# load voxel radiance cache
weight = torch.load('outputs/kitchen/vslf.npz',map_location='cpu')
model = VoxelSLF(weight['mask'],weight['voxel_min'],weight['voxel_max'])
model.load_state_dict(weight['weight'])
for p in model.parameters():
    p.requires_grad=False
    

# get some rays and surface intersection
batch = dataset[1]
rays = batch['rays']
rays_x,rays_d = rays[...,:3],rays[...,3:6]
position = ray_intersect(scene,rays_x.to(device),rays_d.to(device))[0]

# query radiance cache
rgb = model(position.cpu())['rgb']

plt.imshow(rgb.reshape(*img_hw,3).pow(1/2.2))
```

**Comment by dongchen-yang** [comment]
Thanks, it works!

**Comment by dongchen-yang** [comment]
Hi, I have another question. I generated my own data from scratch following [https://github.com/Jerrypiglet/rui-indoorinv-data/blob/fipt/README_indoor_synthetic.md](generate synthetic data from scrach). When I visualize the radiance cahce generated from them, I noticed that some of them are completely dark, which is because it cannot find the rays' intersection point. Do you encounter any similar issues? Thanks in advance!

**Comment by dongchen-yang** [comment]
fixed by loading the cam.txt insntead of the .json file. Seems like the json file has a coordinate orientation issue.

**Comment by Jerrypiglet** [comment]
hey @dyang111 can you detail what were the steps you took which lead to wrong poses? I might want to take a look in case there are bugs (e.g. with the json file).

**Comment by dongchen-yang** [comment]
Sorry for the late reply. Yes, I posted them under [this issue](https://github.com/Jerrypiglet/rui-indoorinv-data/issues/2). I just ran the cmd `python load_mitsubaScene3D.py --scene kitchen_mi --render_2d --renderer blender` to generate the transform.json.
