### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by XinLyu1** [lwwu2/fipt#5]
Hi, thanks for your great work! When I run /demo/relighting.ipynb code, especially mitsuab.load_dict function, it will propose a Segfault issue. So how can I fix it?

**Comment by lwwu2** [comment]
Hi, did you run the code on a multi-GPU machine? If so, can you try to add this code at the very beginning to ensure mitsuba only uses one GPU?
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
```
If this still does not work, it is likely an issue with your mitsuba installation, which I am not sure about the specific error.

**Comment by XinLyu1** [comment]
> Hi, did you run the code on a multi-GPU machine? If so, can you try to add this code at the very beginning to ensure mitsuba only uses one GPU?
> 
> ```
> import os
> os.environ['CUDA_VISIBLE_DEVICES'] = '0'
> ```
> 
> If this still does not work, it is likely an issue with your mitsuba installation, which I am not sure about the specific error.

Thanks for your reply. It seems it's my problem.I have fixed it.
